# Config for workstyle
#
# Format:
# "pattern" = "icon"
#
# The pattern will be used to match against the application name, class_id or WM_CLASS.
# The icon will be used to represent that application.
#
# Note if multiple patterns are present in the same application name,
# precedence is given in order of apparition in this file.

"alacritty" = ""
"kitty" = ""
"github" = ""
"rust" = ""
"google" = ""
"private browsing" = ""
"firefox" = ""
"chrome" = ""
"file manager" = ""
"nemo" = ""
"Team-Chat - AiV" = "󰭻"
"Team-Chat" = "󰭻"
"Chat" = "󰭻"
"com-soeguet-Main"= "󰭻"
"com-soeguet-Main"= "󰭻"
"teamchat8"= "󰭻"
".java"= "󰭻"
".jar"= "󰭻"
"dolphin" = ""
"libreoffice calc" = ""
"libreoffice writer" = ""
"libreoffice" = "󰏆"
"nvim" = ""
"gthumb" = ""
"menu" = ""
"calculator" = ""
"transmission" = ""
"videostream" = ""
"mpv" = ""
"music" = ""
"disk usage" = ""
".pdf" = ""

# programming
"Visual Studio Code" = "󰨞"
"code" = "󰨞"

[other]
fallback_icon = "󰭻"
deduplicate_icons = true
separator = ""
